name: facebook
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management, Routing, and Localization
  get: ^4.6.6

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  #Local Storage (for settings)
  shared_preferences: ^2.2.3

  # Image & File Handling
  image_picker: ^1.1.2
  path_provider: ^2.1.3

  # Notifications
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.3
  # Utilities
  google_fonts: ^6.2.1
  intl: ^0.20.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/locales/